### ISSUE TITLE
阿里云又加限制了?

### ISSUE THREAD

**Issue by jonny77** [messense/aliyundrive-webdav#849] opened 2023-06-24 13:02 UTC
### 问题描述

启动后一直重启

### 重现步骤

启动后一直重启

### 版本

latest

### 运行平台

N1 openwrt

### 日志

stdout: [2m<unknown time>[0m [31mERROR[0m [2maliyundrive_webdav::drive[0m[2m:[0m refresh token failed: Request error: error sending request for url (https://aliyundrive-oauth.messense.me/oauth/access_token): error trying to connect: received corrupt message
stderr: Error: get access_token failed

**Comment by messense** [comment] 2023-06-24 13:04
Duplicate of #844 

自行检查网络能否访问 https://aliyundrive-oauth.messense.me

**Closed by messense** 2023-06-24 13:04 UTC
Labels: bug
