### ISSUE TITLE
jpg图片md5变了 

### ISSUE THREAD

**Issue by LIUBANGJIAN** [messense/aliyundrive-webdav#415] opened 2022-05-04 09:13 UTC
### 问题描述

大佬，你好。我软路由器openwrt开启阿里云盘的webdav功能，然后在centos里用rclone来挂载，然后开启emby来做媒体中心。阿里网盘里已经放好刮削完毕的电影视频文件海报什么的，但是在emby上看到海报只有半张，电影能正常播放。然后我用raidrive来挂载阿里的webdav，用md5g工具来查看海报信息，发现海报的md5已经改变了，海报在此处查看也是不完整的，只有半张。

问题：海报md5不对

### 重现步骤

大佬，你好。我软路由器openwrt开启阿里云盘的webdav功能，然后在centos里用rclone来挂载，然后开启emby来做媒体中心。阿里网盘里已经放好刮削完毕的电影视频文件海报什么的，但是在emby上看到海报只有半张，电影能正常播放。然后我用raidrive来挂载阿里的webdav，用md5g工具来查看海报信息，发现海报的md5已经改变了，海报在此处查看也是不完整的，只有半张。

### 版本

1.3.1

### 运行平台

openwert cnetos docker

### 日志

2022-05-04T09:04:07.377191Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:07.377210Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:07.377219Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:30.773529Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:04:30.773549Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:04:30.882845Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:04:30.882864Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:04:30.882872Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:04:31.005527Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:04:55.315117Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:55.315282Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:55.315292Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:04:55.315302Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:05:20.840954Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:05:20.840977Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:05:20.930403Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:05:20.930420Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:05:20.930428Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:05:47.379646Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:05:47.379668Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:05:47.476526Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:05:47.476545Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:05:47.476561Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.448730Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.448753Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.557279Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.557297Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.557306Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:06:15.724368Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:06:15.918699Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:06:15.918720Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:06:16.014194Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:06:16.014213Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:06:16.014221Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:06:16.104638Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:07:14.553186Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:14.553319Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:14.553328Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:14.561334Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:07:14.561348Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:07:14.809100Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:07:14.809122Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:07:14.809134Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:07:46.098133Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:46.098156Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:46.208033Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:46.208052Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:46.208095Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:07:46.302469Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:08:18.658519Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:08:18.658542Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:08:18.762420Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:08:18.762437Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:08:18.762445Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:08:18.857669Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:08:52.716663Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:08:52.716798Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:08:52.716807Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:08:52.716817Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:09:28.285406Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:09:28.285429Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:09:28.420608Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:09:28.420636Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:09:28.420646Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:09:28.528524Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:09:28.528540Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:09:28.627154Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:09:28.627172Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:09:28.627181Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:09:28.725016Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:10:05.362167Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:05.362302Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:05.362311Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:05.362320Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:10:43.956267Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:43.956283Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:44.053317Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:44.053335Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:44.053344Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:10:44.225412Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:10:44.225432Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:10:44.315915Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:10:44.315931Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:10:44.315938Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:10:44.405888Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:12:06.112112Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:06.112131Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:06.356656Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:06.356676Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:06.356685Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:06.574491Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=627232ceb98bbf7dc45240d0a16fa54a7908a316 marker=None
2022-05-04T09:12:06.740488Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影
2022-05-04T09:12:06.740510Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:12:06.869321Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影
2022-05-04T09:12:06.869341Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影
2022-05-04T09:12:06.869349Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=50168 path=/电影
2022-05-04T09:12:06.961838Z DEBUG aliyundrive_webdav::drive: list file drive_id=50168 parent_file_id=61e14df2301894c7481d4ad6a45c8f9dadead058 marker=None
2022-05-04T09:12:50.221349Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:50.221486Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/电影/人潮汹涌 (2021)
2022-05-04T09:12:50.221495Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/电影/人潮汹涌 (2021)

**Comment by messense** [comment] 2022-05-04 09:21
Duplicate of https://github.com/messense/aliyundrive-webdav/discussions/372

**Closed by messense** 2022-05-04 09:21 UTC
Labels: bug
